# global variables that can be used in any scripts
[global_variable]
    default_title = 'Default Title'
[general]
    check_for_update = false
# global metadata stuff
[metadata]
    # description for the search engine
    description = 'Your application description'
    # robot tags for the search engine
    # available : index, follow, noindex, nofollow
    robots = 'index, follow'
    # charset, default to UTF-8
    charset= 'UTF-8'