# global variables that can be used in any scripts
[global_variable]
    default_title = 'Default Title'
    wiki_name = 'Default Name'
[general]
    check_for_update = false
    # void-wiki use bootstrap. any theme can be added in the css folder. 'theme' must be the name of the css file
    theme = 'purple'
# global metadata stuff, can be overwritten in any of the page/template
[metadata]
    # description for the search engine
    description = 'Your application description'
    # robot tags for the search engine
    # available : index, follow, noindex, nofollow
    robots = 'index, follow'
    # charset, default to UTF-8
    charset = 'UTF-8'